[METADATA]

version = 0.1
description = "A sample prompt for RadPrompter"

[PROMPTS]

system_prompt = "You are a helpful assistant that has 20 years of experience in reading radiology reports and extracting data elements."

user_prompt_intro = """
Carefully review the provided chest CT report (in the <report> tag). Ensure that each data element is accurately captured.

Here is the report:
<report>
{{report}}
</report>

Please pay attention to the following details:
- Your attention to detail is crucial for maintaining the integrity of the medical records. 
- You should not confabulate information, and if something is not mentioned, you should assume that it is `Absent` unless otherwise stated.
- The report may contain additional information that is not relevant to the requested data elements. Please ignore that information.
- We are interested at findings at the time of scan, not the previous ones, so only consider the impression and findings sections of the report.
- Do not print anything else other than the provided output format.
"""

user_prompt_cot = """
I want you to extract the following data element from the report:
{{hint}}

After you provide the data element, I will ask you to provide an explanation and then the final answer.

Now give your initial answer. Then provide a step-by-step explanation based on the information in the report, using no more than three short sentences. You can use less sentences if needed.\
Try to critically appraise your initial answer, which MIGHT be wrong. Then give me your final answer. Format your answers with this format as:

<answer>
<initial_answer>
initial answer goes here
</initial_answer>
<explanation>
1. your first explanation goes here
2. your second explanation goes here (if needed)
3. your third explanation goes here (if needed)
</explanation>
<final_answer>
final answer goes here
</final_answer>
</answer>
"""

user_prompt_no_cot = """
I want you to extract the following data element from the report: 
{{hint}}

Your final answer elements in a valid JSON format and is between <json> and </json> tags:

<json>
{
  "{{variable_name}}": "answer" 
}
</json>
"""

user_prompt_cot_2nd_turn = """
Now, based on your expalanation, provide your final answer elements in a valid JSON format and is between <json> and </json> tags:

<json>
{
  "{{variable_name}}": "answer" 
}
</json>
"""

assistant_response_template = """
<json>
{
  "{{variable_name}}" : \""""


[CONSTRUCTOR]
system = "rdp(system_prompt)"
user = [
"rdp(user_prompt_intro + user_prompt_cot)"
,
"rdp(user_prompt_cot_2nd_turn)"
]
stop_tags = [
"</answer>"
,
"</json>"
]
response_templates = [
"<answer>\n<initial_answer>"
,
"rdp(assistant_response_template)"
]


[SCHEMAS]

[SCHEMAS.PulmonaryEmbolism]
variable_name = "Pulmonary Embolism"
type = "select"
options = ["Present", "Absent"]
hint = """"Indicate `Present` if the report explicitly mentions the patient has pulmonary embolism in their CT scan. 
Indicate `Absent` if pulmonary embolism is not seen or if a previously observed pulmonary embolism is mentioned as resolved."""
show_options_in_hint = true

[SCHEMAS.Laterality]
variable_name = "Laterality"
type = "select"
options = ["Left", "Right", "Bilateral", "Not Mentioned"]
hint = """
Indicate `Left` if the report explicitly mentions the patient has a left-sided pulmonary embolism in their CT scan. 
Indicate `Right` if the report explicitly mentions the patient has a right-sided pulmonary embolism in their CT scan. 
Indicate `Bilateral` if the report explicitly mentions the patient has a bilateral pulmonary embolism in their CT scan or if patient has both left and right sided pulmonary embolism.
Indicate `Not Mentioned` if side of pulmonary embolism is not mentioned.
"""
show_options_in_hint = true


[SCHEMAS.Acuity]
variable_name = "Acuity"
type = "select"
options = ["Acute", "Chronic", "Mixed", "Not Mentioned"]
hint = """
Indicate `Acute` if the report explicitly mentions the patient has an acute pulmonary embolism in their CT scan. 
Indicate `Chronic` if the report explicitly mentions the patient has a chronic pulmonary embolism in their CT scan. 
Indicate `Mixed` if the report explicitly mentions the patient has a acute on chronic pulmonary embolism in their CT scan. 
Indicate `Not Mentioned` if acuity of pulmonary embolism is not mentioned.
"""
show_options_in_hint = true
